---
ufw_default_rules:
  - comment: Allow SSH from local network
    direction: in
    from_ip: 192.168.1.0/24
    to_port: '22'
    proto: tcp
    rule: allow

  - comment: Allow SSH from vpn network
    direction: in
    from_ip: 10.0.1.0/24
    to_port: '22'
    proto: tcp
    rule: allow

  - default: deny
    state: enabled

ufw_rules: "{{ ufw_default_rules }}"