---
- name: Set up firewall
  include: setup-firewall.yml

- name: Set up nextcloud
  include: setup-nextcloud.yml

- name: Set up vpn
  include: setup-vpn.yml

- name: Set up monitoring
  include: setup-monitoring.yml

- name: Set up backup
  include: setup-backup.yml
