---
# tasks file for ansible-private-cloud

- name: Set up firewall
  hosts: instance
  tasks:
    - name: Ensure ufw is present
      package:
        name: ufw
        state: present

    - name: Ensure ufw rules are present
      ufw: "{{ item }}"
      with_items: "{{ ufw_rules }}"
  tags:
    - firewall

- name: Provision nginx
  hosts: instance
  roles:
    - name: nginxinc.nginx
      vars:
        nginx_install_from: os_repository
  tags:
    - nginx

- name: Provision mysql
  hosts: instance
  roles:
    - name: geerlingguy.mysql

- name: Provision nextcloud
  hosts: instance
  roles:
    - name: nextcloud
  tags:
    - nextcloud

- name: Provision wireguard role
  hosts: instance
  roles:
    - name: wireguard
  tags:
    - wireguard

- name: Provision monitoring
  hosts: instance
  roles:
    - name: node-exporter
    - name: alertmanager
    - name: prometheus
  tags:
    - monitoring