---
- name: Provision nextcloud
  hosts: instance
  roles:
    - name: nginxinc.nginx
        vars:
          nginx_install_from: os_repository
    - name: geerlingguy.mysql
    - name: nextcloud
  tags:
    - nextcloud