---
- name: Provision firewall
  hosts: all
  tasks:
    - name: Ensure ufw is present
      package:
        name: ufw
        state: present

    - name: Ensure ufw rules are present
      ufw: "{{ item }}"
      with_items: "{{ ufw_rules }}"
  tags:
    - firewall